# Generated by Django 5.2.11 on 2026-02-20 06:31

import jobapi.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, validators=[jobapi.models.validate_minimum_name_length])),
                ('email', models.EmailField(help_text='Enter a valid email address', max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, validators=[jobapi.models.validate_phone_number])),
                ('is_admin', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
