# Generated by Django 5.2.11 on 2026-02-20 09:14

import django.db.models.deletion
import jobapi.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, validators=[jobapi.models.validate_minimum_name_length])),
                ('description', models.TextField(max_length=500)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapi.jobuser')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applied_on', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapi.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapi.jobuser')),
            ],
            options={
                'ordering': ['-applied_on'],
            },
        ),
    ]
